### ISSUE TITLE
ShinyEgg bot keeps closing itself

### ISSUE THREAD

**Issue by Vamp55** [kwsch/SysBot.NET#1]
The ShinyEgg bot keeps showing this "**Box 1 Slot 1 not empty. Move this Pokemon before using the bot!**"& closes itself even when I don't have any pokemon in box 1.  

Game - Pokemon Sword v1.1.0

**Comment by Bappsack** [comment]
Can't confirm.

It checks if Box 1 Slot is a Egg or blank.

Make sure u are using the latest sys bot base.

**Comment by Vamp55** [comment]
I am using the latest stable release of sys bot base. Injection is also not working. 

https://drive.google.com/file/d/1BtqWVaxqlKeiipC9_BXDSW-WrbZoW1Xc/view?usp=sharing

**Comment by kwsch** [comment]
Resolved on Discord; can't have any cheats active (edizon)
