### ISSUE TITLE
The server responded with error 403: Forbidden and no link code was entered

### ISSUE THREAD

**Issue by kresellekey** [kwsch/SysBot.NET#10]
I keep getting this error any time someone tries to use $seedcheck, what does this error mean and how would I go about fixing it? It doesn't seem to affect the bot starting up but it never enters a link code as well, so it just finds a random person instead of putting in the code it specifies

**Comment by kwsch** [comment]
With Discord, a 403 error means that the bot had insufficient permissions and/or arguments to complete the task. 

Double check the settings you've granted for the bot; I'm assuming it fails to private message the trade partner.

**Comment by kresellekey** [comment]
funnily enough the bot still works fine, it just shows that message sometimes. Also managed to fix the link code issue as my text speed was on normal. Changing it to fast fixed it! Will close the thread now thanks for all the help :)
