### ISSUE TITLE
[feature] configure socket connect timeout

### ISSUE THREAD

**Issue by ca1e** [kwsch/SysBot.NET#117]
https://github.com/kwsch/SysBot.NET/blob/75f57bdf5d5d53e874205fa53597029ddfb63953/SysBot.Base/Connection/Switch/Wireless/SwitchSocketSync.cs#L20

```
Log("Connecting to device...");
            //Connection.Connect(Info.IP, Info.Port);
            var result = Connection.BeginConnect(Info.IP, Info.Port, null, null);

            bool success = result.AsyncWaitHandle.WaitOne(5000, true);
            if (success)
            {
                Connection.EndConnect(result);
            }
            else
            {
                Connection.Close();
                throw new SocketException(10060); // Connection timed out.
            }
            Connected = true;
            Log("Connected!");
```

**Comment by ca1e** [comment]
As I posted above,I do recommanded we should handle timeout when connect socket,It'll avoid meaningless waiting and save our time

**Comment by Lusamine** [comment]
While this conceptually makes sense, my experience has been that connection failures are fairly immediate, and the user knows right away that they need to fix their connection problems before trying again.  Are you having a different kind of problem that is prolonged and meaningless waiting?

**Comment by ca1e** [comment]
yes,thats the point.The Connect` have a LONG timeout over 20 seconds by DEFAULT when there are connection failures, users should know immediatly when the connection success or have a failure.

**Comment by Lusamine** [comment]
I am not considering this high priority at all for 20 seconds.  I tried it myself, it discloses to you that it has crashed, and gives you the opportunity to fix it before trying again.  It is immediately obvious that the connection is not working (no messages, no green light) before the bot crashes.

**Comment by ca1e** [comment]
Seems like we are talking about different things Lol.I just provide an improve,there are not any diffrence between before except a shortly timeout.
