### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by Kakashiden** [kwsch/SysBot.NET#122]
I am trying to the SysBot to trade only one Pokemon, say Marshadow, but to every user who trades with the bot. I have The Marshadow file from PKHex loaded into my SysBot program, and nobody in the que. I have the Distrubute Folder path set to C:\Users\Kakashi\Desktop\Pokebot\Sysbot\distribute , and the Dump Folder set to C:\Users\Kakashi\Desktop\Pokebot\Sysbot\dump. My Distribution settings are set to:
DistributWhileIdle - True
Shuffled - False
LedySpecies - None
LedyQuitIfNoMatch - False
Trade Code - 71717171
Random Codes - False

When I start the Bot I am on Link Trade

I can successfully upload a pokemon file in discord using the $trade command to initiate and complete trades with no problem. 
The issue comes in when there isn't a queue. How do I get the bot to start using the set TradeCode to Trade the Pokemon files in the distribute folder when there is no queue?

Thanks for any information in advanced!

**Comment by Lusamine** [comment]
It should automatically occur if you set it up correctly.  See the wiki for the setup.

This isn't an issue with the program so I'm closing this
