### ISSUE TITLE
Web Interface for SysBot.NET

### ISSUE THREAD

**Issue by qelix** [kwsch/SysBot.NET#127]
Hey, 

I know that this issue is a bit out of scope for this project, as this is "just" the library, but I was wondering if there is a web interface implementation for it. I couldn't find anything on Google and I don't like the UX of using Discord bots. 

Thanks in advance :)

**Comment by Lusamine** [comment]
The bot does run on Twitch and you can find active ones there, but if you are looking for something specifically on a webpage, someone else would have to make one.
