### ISSUE TITLE
I'm trying to access the SysBot-x64 on the Azure DevOps.

### ISSUE THREAD

**Issue by izzybear666** [kwsch/SysBot.NET#132]
I would like to access this file to help me out alot. I understand the risks and everything. I would love to use it soo i can progress in what im doing. Please get in contact with me at your convenience. Thank You.

**Comment by Lusamine** [comment]
The automatic build is already linked on the wiki: https://github.com/kwsch/SysBot.NET/wiki/Bot-Startup-Details
