### ISSUE TITLE
Suspicious Activity

### ISSUE THREAD

**Issue by AnthonieZ87** [kwsch/SysBot.NET#138]
Been running the bot trading Pokémon for Pokémon Legends Arceus and noticed in the log some were cancelled and it  was saying it was due to Suspicious Activity.
What constitutes as Suspicious Activity?

**Comment by kwsch** [comment]
If you have abuse settings defined (you likely do), Ledy trades prevents users from receiving multiple high value trades in a short period of time.

The idea is that players are not allowed to hog your bot farming legendaries to trade away to other users for their own giveaways/trade threads.
