### ISSUE TITLE
Twitch integration

### ISSUE THREAD

**Issue by k20stitch** [kwsch/SysBot.NET#140]
I'm hoping I'm not an idiot as I read through all of the documentation (as vague as it is). I'm able to get my twitch bot to announce it self and even does the whole count down thing when setting distribute on idle, but it will not accept chat commands. I've tried from my main account and had others try as well. using both the default $ and also tried ! but neither $help or !trade produce anything in the chat from the bot.

**Comment by kwsch** [comment]
It's working for everyone else; you likely misconfigured the command prefix in the settings.

Some settings are not reloaded until you restart the program, so try that too.

**Comment by k20stitch** [comment]
Just realized all of the commands work, except help.

**Comment by Lusamine** [comment]
$Help is not supposed to work on Twitch (it would not format right).

It's only listed under Discord: https://github.com/kwsch/SysBot.NET/wiki/Discord-and-Twitch-Commands

**Comment by k20stitch** [comment]
ah, thank you. The ReadMe I have is ancient. Thanks.
