### ISSUE TITLE
PKHeX.Core.AutoMod.dll outdated

### ISSUE THREAD

**Issue by easyworld** [kwsch/SysBot.NET#143]
Return value of [FlawlessIVCount](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic.cs#L32) changed in this [commit](https://github.com/kwsch/PKHeX/commit/50828fa1bb496e4b5499314a9bc16edbeee9266d). That cause "System.MissingMethodException: Int32 PKHeX.Core.EncounterStatic.get_FlawlessIVCount()". Update PKHeX.Core.AutoMod.dll in SysBot.Pokemon/deps may solve this problem

**Comment by Lusamine** [comment]
This is known and is awaiting updates for the dependency.
