### ISSUE TITLE
Ryujinx Support for LDN (LAN and normal)

### ISSUE THREAD

**Issue by SquidOrigins** [kwsch/SysBot.NET#147]
I want to use Sysbot on Ryujinx for Automating LAN Trading

**Comment by Lusamine** [comment]
Sounds like you are a pirate or you want to trade very illegal Pokémon.  This is indeed an important issue, but neither will ever be supported, so please do not ask here.  Buy the games and play them on your Switch.

**Comment by Volcan4436** [comment]
> Sounds like you are a pirate or you want to trade very illegal Pokémon. This is indeed an important issue, but neither will ever be supported, so please do not ask here. Buy the games and play them on your Switch.

i own the games and have switches i was just wanting to use Ryujinx For LAN mode but it isn't needed anymore
