### ISSUE TITLE
sysbot not using OT name using showdown method

### ISSUE THREAD

**Issue by Foxfire2121** [kwsch/SysBot.NET#149]
Hello. Im wondering if someone may be able to help me out. My bot for some reason isnt displaying the OT name when trying to gen mon. Its only using my bots OT name. Here is an example of what they did. 

Giratina-Origin @ Griseous Orb
OT: Christopher
Ability: Levitate
Shiny: Yes
Ball: Master Ball
EVs: 6 Def / 252 SpA / 252 Spe
- Ancient Power
- Dark Pulse
- Earthquake
- Poltergeist

im not too sure why. Im VERY VERY new to all this and learning as i go. I took my OT name off  so nothing was there. after i did that showdown sets stopped working completely. im struggling a bit. lol. thanks to anyone that can help! appreciate anyone's time!

**Comment by Lusamine** [comment]
This set worked fine for me in SWSH on latest release (I just downloaded it to check with `$convert`).  When requesting help with any program, it's most helpful to provide as much information as possible so another person who doesn't know anything about what you're doing can replicate the problem. Show pictures if you're unable to explain it.

Some examples of information that would be important to provide:
- What game are you doing this in?
- What command did you type to do this?
- What are your Legality settings on the Hub?
- When did you last update the program?
- What do the logs say (both in the program and text logs)?
- What Pokemon was generated instead?

These are my settings and this is what I got.
![image](https://user-images.githubusercontent.com/30205550/184050894-81dde83d-3c80-4db1-9e1c-ee0f9a4f2256.png)
![image](https://user-images.githubusercontent.com/30205550/184050919-607d4835-4815-4361-b2c1-19befc99c687.png)

**Comment by Foxfire2121** [comment]
thank you so much for the quick reply! 

- game = SWSH
- im not sure what you mean by "what command did i use" - my bot is on a server and a member DM me letting me know that the bot didnt give what he requested w HIS OT. it used my bots OT. 
- i recently updated the bots, id say within the past month 
 
here is the image
![Screenshot 2022-08-10 215206](https://user-images.githubusercontent.com/101741539/184052334-bfacf007-0601-4dcf-ba92-99428d428352.png)


thank you again for your reply.

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/184052484-89133778-95fa-4261-a67e-7c412dc2506a.png)
You did not allow users to override the trainer data, so it makes sense that it's not doing it.

This is explained on the Legality page: https://github.com/kwsch/SysBot.NET/wiki/Legality

In the future, I would suggest using the support Discord linked [on the main page](https://github.com/kwsch/SysBot.NET) for help running the program. Issues on GitHub are for problems with the program code.

**Comment by Foxfire2121** [comment]
i do see a difference now looking at how yours is set up. i have missing 
- MGDBPath
- GeneratePath Trainer info 
- also Reset Home Tracker is True on mine and False on yours. 
im not sure what that is. i followed a tutorial when doing this and i believe those parts were skipped or left blank so i did the same since im not sure what to do about that.

**Comment by Foxfire2121** [comment]
i see - sorry about that. I searched for help and it brought me here. But will do that. Thanks for your help

**Comment by Lusamine** [comment]
The only guide we recommend officially is the Wiki on this page.  Other tutorials are not affiliated with us and may provide old or out-of-date information.

All of these settings are explained on the Legality page I linked above.

**Comment by Foxfire2121** [comment]
i will go through that and joined the discord group mentioned. thanks again!
