### ISSUE TITLE
sysbot input doesn't work when docked

### ISSUE THREAD

**Issue by k20stitch** [kwsch/SysBot.NET#153]
Latest firmware, latest release of sysbot, latest cfw.

When starting Sysbot with the switch docked, the inputs don't work and it finds itself in an unexpected state. To resolve, I have to undock the switch, start sysbot, and then re-dock the switch.

**Comment by Lusamine** [comment]
Shouldn't be an issue. Try disconnecting your joycons entirely from the settings before starting.
