### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by PokeNebula** [kwsch/SysBot.NET#156]
[PokeNebula](https://github.com/PokeNebula) commented [9 minutes ago](https://github.com/kwsch/SysBot.NET/issues/new#issue-1508354713)
I’ll try to give details!
I’m able to connect with my IP address on my switch with FileZilla just fine. When I boot the sysbot the box turns green and it searches for my trainer. After about 20 seconds the box turns white and shows the detaching controllers message (even though my controllers are off and detached) and I notice on my filezilla it will say error: disconnection after 20 seconds of inactivity.
May I have some help on this pretty please? I hope these details help

**Comment by Lusamine** [comment]
Read the error logs to know what the issue is. The logs are in the tab called "Logs" or in a folder named "logs".
Follow all the instructions in Wiki > Troubleshooting Connection Errors if looking at the logs does not fix your problem.
This isn't an issue with the program, and the problem can be solved by looking at what the program tells you or the documentation.

**Comment by PokeNebula** [comment]
I’ll definitely give this a shot and check the wiki again! Thank you! If I come across anything I’ll let you know! I’m sure it’s something small probably something I overlooked

**Comment by PokeNebula** [comment]
May I ask one last question please? I followed the wiki and checked the instructions on the logs. Everything seems to work fine but when I enter $hi in the discord to test the bot it doesn’t respond. Any idea what the issue may be? Or could you point me to another resource?

**Comment by Lusamine** [comment]
Not a problem with the program, but an issue with how you've set things up on the Discord side of things.

See the "Discord Integration" page. If the bot shows up online, then you need to figure out how to configure permissions in your server so the bot can see the channel. If you restricted channels in the config, then you need to whitelist them. This is also discussed in the Wiki.
