### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zpanther1** [kwsch/SysBot.NET#158]
My discord trade bot has been working all day fine. But now there is this error message popping up. I have tried restarting the program and my game but it  is still not working.
<img width="358" alt="Capture" src="https://user-images.githubusercontent.com/120697115/209884581-f5c7fcba-e49b-453a-a5f3-95c191c8b571.PNG">

**Comment by Lusamine** [comment]
Your set is illegal.

Post the set if you've validated it on Showdown and it is legal there.

**Comment by Zpanther1** [comment]
I did one through showdown and it said it was valid for gen 9 ubers

**Comment by Zpanther1** [comment]
I did this and same results $trade Pikachu (M) @ Master Ball
Ability: Static
Shiny: Yes
Tera Type: Electric
EVs: 48 HP / 32 Atk / 20 Def / 28 SpA / 128 SpD / 252 Spe
- Agility
- Body Slam
- Brick Break
- Discharge

**Comment by Lusamine** [comment]
Where is the Wo-Chien set?

**Comment by Zpanther1** [comment]
Wo-Chien @ Master Ball  
Ability: Tablets of Ruin  
Tera Type: Dark  
EVs: 88 HP / 72 Atk / 56 Def / 48 SpA / 40 SpD / 36 Spe  
- Body Press  
- Body Slam  
- Energy Ball  
- Facade

**Comment by Zpanther1** [comment]
Both didint work though

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/209892977-5cc15391-63e8-478e-9b10-88b108369ab1.png)
Both of these work fine for me. I don't think you are on the latest version, or you have old files interfering with new ones.

I would suggest starting over and setting this up again in a new folder.  Copy important settings over from your previous config.
