### ISSUE TITLE
Can't get Dudu Bot to connect to my switch.

### ISSUE THREAD

**Issue by JanStegemann** [kwsch/SysBot.NET#16]
I have everything setup, like its supposed to be.
Got the dlls in the folder, got the latest version of sys botbase installed and no wireless controllers attatched.

Still the bot wont do anything on my switch. In the logs it says "SwitchConnectionAsync: Grabbing trainer data of host console...".
When I use a command on discord it just says it added me to the queue and then does nothing.

**Comment by hp3721** [comment]
Try going into "Options" in the game and go into lan mode with L+R+Left Joystick Down or if you can go into the y-comm and press + to connect to the internet. Then, try connecting again with the bot.

**Comment by architdate** [comment]
Have you verified that your sys-botbase is functioning properly?

**Comment by JanStegemann** [comment]
I got it to work by restarting my switch. Thanks for the tips anyways ^^
