### ISSUE TITLE
Error connecting to Twitch account

### ISSUE THREAD

**Issue by ProfOakLab** [kwsch/SysBot.NET#161]
I tried to find any kind of help before I wanted to submit an issue so I want to apologize if this is an easy fix that I can't fix myself

I finally got the bot to not crash when I enter my Twitch bot information. But now i'm getting this in the logs and I have no idea what to do

![e1efb5efbbb562ec5817562a1aff788a](https://user-images.githubusercontent.com/122359228/211528941-34eb0e25-a9f5-4abc-86c3-df638591791d.png)

**Comment by Lusamine** [comment]
You need to look harder then because this is in Wiki > Troubleshooting.
