### ISSUE TITLE
More than a different raid with sysbot.net

### ISSUE THREAD

**Issue by carpspirit02** [kwsch/SysBot.NET#168]
Good evening. Could someone explain to me how to make Sysbot change from Seed (raid) on its own? I see several Discord or the bot offers several different raids in a row. Thank you very much

Example in photo![image](https://user-images.githubusercontent.com/79032023/224206375-7f06ef4f-15f6-497c-84f8-431622fbb802.jpeg)

**Comment by Lusamine** [comment]
This is not our program. We do not have raid features. Ask the owner of the fork.
