### ISSUE TITLE
Profanity filter?

### ISSUE THREAD

**Issue by notcreativeorcool** [kwsch/SysBot.NET#170]
Is there kind of profanity filter in the sysbot preventing me from creating mons with my OT? Didnt have this problem til about a month ago, mons showing up with game name “Scarlet” and someone said they believed my IGN was one letter off from a racial slur.

tl;dr cant create a pokemon with my OT

**Comment by Lusamine** [comment]
1. This is not a repo for bot users. Questions about bot usage go to the bot host.
2. What you're describing sounds like an issue with GF filters triggering on profanity in your OT. To test this, manually trade a Pokémon from your own save and see if it changes the OT.

SysBot does not change profanity into "Scarlet", and as such, this is not a problem with the program.
