### ISSUE TITLE
GetGameInfo version with trailing zero in usb-botbase

### ISSUE THREAD

**Issue by easyworld** [kwsch/SysBot.NET#172]
```
await SwitchConnection.GetGameInfo("version", token).ConfigureAwait(false);
```
[This code](https://github.com/kwsch/SysBot.NET/blob/master/SysBot.Pokemon/SV/PokeRoutineExecutor9SV.cs#L84) returns the hex value `312E322E30000000000000000000000000` in [usb-botbase](https://github.com/Koi-3088/usb-botbase/releases/latest), which results in the error message `USB-3: Game version is not supported. Expected version 1.2.0, and current game version is 1.2.0`

Perhaps getting the trimmed result would be better?

**Comment by Lusamine** [comment]
Did this PR not fix it?

https://github.com/kwsch/SysBot.NET/pull/171

**Comment by easyworld** [comment]
I apologize, my branch is not up to date.
