### ISSUE TITLE
I can't find the bot with the link code entered

### ISSUE THREAD

**Issue by Gillian2013** [kwsch/SysBot.NET#178]
Hi, Im trying to set up sysbot and finally have it running but when i enter the code on my other switch it just keeps saying no one can be found. Anyone got any ideas what could be wrong?

Im just doing a sysbot, im not connecting it to Dsicord

**Comment by Lusamine** [comment]
Question is too vague.
I can't tell if your Switch is even hacked.
You didn't use your eyes to look at the Switch and describe what is happening.
You didn't give anything in the error logs.
Any number of problems could be causing what you described.

Read the wiki for proper setup and troubleshooting. The issues are for errors with the program, not user errors.

https://github.com/kwsch/SysBot.NET/wiki
