### ISSUE TITLE
Redundant content in Wiki

### ISSUE THREAD

**Issue by easyworld** [kwsch/SysBot.NET#183]
In [General-Settings.md](https://github.com/kwsch/SysBot.NET/wiki/General-Settings/_compare/fa4b7b0%5E...fa4b7b0#diff-fee0d1190d75c39b66ddd7d9b628ae133d3d338a76d1f49a7aa56d7d9db2ded5). AntiIdle appeared twice.
<img width="1234" alt="image" src="https://github.com/kwsch/SysBot.NET/assets/8280291/cea6606d-2570-48c9-ba68-38d2716ea35f">

**Comment by Lusamine** [comment]
Fixed now. I accidentally duplicated it yesterday updating it for some new features to-be-added.
