### ISSUE TITLE
is there a way to run this on my switch without connecting to nintendo online

### ISSUE THREAD

**Issue by dwalker615** [kwsch/SysBot.NET#184]
Hi! my nintendo switch got banned not sure exactly what for, but i was wondering if there is a way for me to continue to use this offline for my family on my network, it always hangs trying to connect to the internet

**Comment by teward** [comment]
If your nintendo switch is banned, you're out of luck - literally out of luck, because that device is now permanently blacklisted and not going to work anymore with things.

To my knowledge, Sysbot.NET requires the Online functionality to function, and if your switch is banned you're out of luck.

**Comment by kwsch** [comment]
This repo does not support local/LAN trades.

You know why you were banned.
