### ISSUE TITLE
Errors connecting 

### ISSUE THREAD

**Issue by Bluekinky81** [kwsch/SysBot.NET#188]
I keep getting two errors.
No connection could be made because the target machine actively refused it.

Connection failed, host failed to respond. (Short and right to the point) We tried to update all programs, we've reboot and restarted several times, and delete and install again, nothing seem to be working. The wifi router was reset too and still have error. 

Anyway suggestions and help?

**Comment by kwsch** [comment]
Read the wiki. Your computer cannot establish a connection with your console.
