### ISSUE TITLE
Can you add Dodo app integration

### ISSUE THREAD

**Issue by fanyue1117** [kwsch/SysBot.NET#189]
It's troublesome to use discord or twitter in Chinese Mainland. Can you support of the dodo app？
https://www.imdodo.com/
thanks

**Comment by BakaKaito** [comment]
There is a fork that supports Dodo found here: https://github.com/easyworld/SysBot.NET

**Comment by fanyue1117** [comment]
Thank you very much, but it seems that this project has been suspended for a long time and cannot adapt to the current new version.

**Comment by kwsch** [comment]
Incorrect; the above linked project was last updated when PKHeX last updated (October).

This main repo is not intended to provide an integration to every service possible, especially those that are not common internationally or to the repo's developers. You're more than welcome to use that fork as linked above.
