### ISSUE TITLE
[feature request] Trading entire teams

### ISSUE THREAD

**Issue by jpoep** [kwsch/SysBot.NET#194]
Hey, thanks for the great project!

Are there any plans to support trading entire teams instead of single Pokemon one by one? We're using this project for our Pokemon draft league and it would be so much faster if there was a way for it to generate an entire team of 6 Pokemon at once and proceed to trade them all without ever quitting out of the trade menu.

I must admit that I haven't been able to read the whole documentation, but digging into the code responsible for trading a single Pokemon in SV suggested that the bot will always quit out of the trade menu upon a successful trade, so I'm assuming this feature isn't implemented. I also couldn't find any issues related to this.

Are there any obvious problems with this approach that I'm not seeing? It does look like a lot of work for this to behave correctly, but I'm definitely tempted to give the implementation a try on my own if you're up for PRs.  

I'd love to hear the maintainers' thoughts on this! :)

**Comment by kwsch** [comment]
These bots are intended to be single-trade, and multi-trade is never implemented to prevent hogging / bulk selling.
