### ISSUE TITLE
[Wiki] Link to Zadig appears to be dead

### ISSUE THREAD

**Issue by Lincoln-LM** [kwsch/SysBot.NET#195]
The link to Zadig on [this page](https://github.com/kwsch/SysBot.NET/wiki/Configuring-a-new-USB-Connection) appears to be dead as unitrunker no longer hosts the HTML file.

https://zadig.akeo.ie/ is what seems to be the official site and https://github.com/pbatard/libwdi/releases seems to be the github for it so I would think either would work as a replacement.

**Comment by kwsch** [comment]
Revised, thanks!
