### ISSUE TITLE
Possibility to run SysBot with Discord on a banned Switch

### ISSUE THREAD

**Issue by domx176** [kwsch/SysBot.NET#196]
Hello there!

I want to know if there is a possibility to run the Bot normally but instead of making the Game (In my case Pokemon Violet) connecting to the Internet it should stay offline/n LAN so I can trade with myself. My V1 is unfortunately banned and neither do I have the soldering skills nor the chip to make my Switch Lite hackable (which would be obsolete as this is my main console. I do have some small knowledge on C# but I just didnt get to the point where to edit the source code. To keep it short:

V1 Banned Switch, Hacked and fully working, acting as the trade partner bot but only for myself - should only stay offline ingame
Switch Lite /Mariko on OFW as the receiver
Trades via Discord as usual/commonly used

I appreciate any help or hint into the right direction, I also do not consider releasing/forking edited source code to public if I get help to that. If not, I appreciate the time for reading this. 

Faithfully

Dominik

**Comment by domx176** [comment]
Can be archived/deleted, I just overlooked an issues from some months ago, sorry.

**Comment by Lusamine** [comment]
For future reference, the developers of this repo will not be providing support/assistance for running trade programs on a banned console or over LAN networks. This use case is very frequently for trading extremely illegal Pokémon or because of piracy.
