### ISSUE TITLE
SpA/SpD/Spe being assigned wrong values on trade

### ISSUE THREAD

**Issue by bdawg1989** [kwsch/SysBot.NET#199]
Latest Sysbot does not assign correct EV values.

Example showdown set:
```
Azumarill  
Ability: Thick Fat  
Tera Type: Water  
EVs: 252 HP / 4 Atk / 252 SpA  
Quiet Nature  
- Alluring Voice  
- Aqua Jet  
- Aqua Tail  
- Blizzard
```
Output File:

[0184_-_Azumarill_-_D0BE40EDB533.zip](https://github.com/kwsch/SysBot.NET/files/15214256/0184_-_Azumarill_-_D0BE40EDB533.zip)

Assigns SpD instead of SpA

![image](https://github.com/kwsch/SysBot.NET/assets/80122551/54948edb-a2d5-4b0d-8a75-d5c96abefa96)

I thought it was due to PKHeX not having the values in correct order that showdown expects, but that didn't work either.

```
    /// <summary>
    /// Retrieves the EVs of the PKM in the order HP, ATK, DEF, SPE, SPA, SPD
    /// </summary>
    /// <param name="value">Span of length 6 to write the EVs to</param>
    public void GetEVs(Span<int> value)
    {
        if (value.Length != 6)
            return;
        value[0] = EV_HP;
        value[1] = EV_ATK;
        value[2] = EV_DEF;
        value[3] = EV_SPE;
        value[4] = EV_SPA;
        value[5] = EV_SPD;
    }

    /// <summary>
    /// Sets the EVs of the PKM in the order HP, ATK, DEF, SPE, SPA, SPD
    /// </summary>
    /// <param name="value">Span of length 6 to read the EVs from</param>
    public void SetEVs(ReadOnlySpan<int> value)
    {
        if (value.Length != 6)
            return;
        EV_HP = value[0];
        EV_ATK = value[1];
        EV_DEF = value[2];
        EV_SPE = value[3];
        EV_SPA = value[4];
        EV_SPD = value[5];
    }
    ```

**Comment by kwsch** [comment]
Not able to replicate with any of the unit tests using this repo's latest commit.

**Comment by bdawg1989** [comment]
Ah, I just realized that even though I downloaded the latest sysBOT commit to test, I replaced PKHeX.Core.dll in the nuget package with the latest commits too.

**Comment by Lusamine** [comment]
Issues are for problems with the current latest commit, not with custom builds or future releases. Closing this since you are using a custom build with a different core. If the issue persists after sysbot is updated for the new core, please re-open it.

**Comment by bdawg1989** [comment]
@kwsch I figured this one out btw...  I re-ordered these correctly and it started working right again.

In PKHeX.Core > ShowdownSet

```
private static readonly string[] StatNames = ["HP", "Atk", "Def", "Spe", "SpA", "SpD"];
```

Changed to:
```
private static readonly string[] StatNames = ["HP", "Atk", "Def", "SpA", "SpD", "Spe"];
```

Before:
![EV-Ordering_EVChange](https://github.com/kwsch/SysBot.NET/assets/80122551/c693c04c-f797-4d1d-9468-585a6b32c2ae)

After:
![EV-Ordering_EVFixed](https://github.com/kwsch/SysBot.NET/assets/80122551/432d30fa-e456-47b5-96a3-d8bb112b53b6)
