### ISSUE TITLE
The latest PKHeX shows Pokemon as Invalid, but the latest SysBot can distribute it.

### ISSUE THREAD

**Issue by VYXUOF** [kwsch/SysBot.NET#206]
I'm very sorry, English is not my native language, so there might be spelling errors. Today, when I used the latest SysBot, I found that this Pokémon could be distributed, but PKHeX marked it as illegal. Based on my experience, I also believe it is not legal. Below is the link to the software I downloaded. I also tried the SysBot version from July 26th, and it could also distribute the Pokémon. I've included the file for this Pokémon in a compressed folder.

download link address:
https://projectpokemon.org/home/files/file/1-pkhex/       ver:PKHeX 24.11.11
https://projectpokemon.org/home/files/file/4207-sysbotnet-automatic-build/     ver:SysBot.NET Automatic Build 20241115.1
![20241116113255](https://github.com/user-attachments/assets/1fb1a193-6c20-47f6-8d0c-9c17df89ce3a)

[0123 ★ - ストライク.zip](https://github.com/user-attachments/files/17783296/0123.-.zip)

**Comment by kwsch** [comment]
The log will mention that the file is not legal.
If you've disabled transfer checks (HOME Tracker), then it is permitted.

**Comment by VYXUOF** [comment]
> If you've not enabled HOME transfer checks, then it is permitted.

Thank you for your reply. I double-checked the wiki and found this specific detail. Now, it’s clear that they indeed cannot distribute it.
