### ISSUE TITLE
Request : multiple eggs farming

### ISSUE THREAD

**Issue by LeMageFro** [kwsch/SysBot.NET#24]
Hello,

I'm not sure if this is the best place to submit this request since it's not an issue, so I apologize in advance if it is not.
Is there any plan to add the option to farm more than one shiny egg at once, as long as the n first slots of the first box are free ? Ideally the number of eggs desired could be set in the parameters.
The option to keep non shiny eggs with 6 perfect IV could also be useful (this one would just be for convenience though since we can get them back from the dump folder and inject them with PKHeX).

Thanks a lot for this amazing tool !

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/SysBot.NET/pull/26
