### ISSUE TITLE
Issue of making .exe file

### ISSUE THREAD

**Issue by Deos0310** [kwsch/SysBot.NET#33]
I'm also suffering from making this .sln file into .exe file, and also I have no idea what sdk file this error is requiring.. I just have seen your answer that there is a .exe file that already made at the azure pipelines cloud service. Can you tell me how can I utilize it just a little bit?

**Comment by kwsch** [comment]
Without seeing the error messages, can't tell what you are missing.

Find the green check mark for an individual commit, and click through the pages to download the artifact.
