### ISSUE TITLE
Building Solution error..

### ISSUE THREAD

**Issue by Deos0310** [kwsch/SysBot.NET#34]
![ERROR](https://user-images.githubusercontent.com/61553694/75470518-252f0a00-59d4-11ea-81eb-d78d7187bb31.png)

I brought all of  these error messages, all I have done is just downloaded all of your sln files and tried to build it.

I have no idea what does 'z3 something' means, and how can I solve it. Can you help me?

me and my colleague are suffering with this problem for about more than half day.

Thank you for your kind informing and also sorry for too many questions.

**Comment by Bappsack** [comment]
Select the x64 Build Option
