### ISSUE TITLE
running bot error

### ISSUE THREAD

**Issue by ttnt5** [kwsch/SysBot.NET#39]
![error](https://user-images.githubusercontent.com/61551694/75601312-2f98f300-5afd-11ea-8aad-b471095d9100.jpg)
i run bot well yestereday
but i run raidbot and error happened
discord run well but not make pkm8 pokemon 
i install new version and running bot
but i still error happened

**Comment by Lusamine** [comment]
What's in your distribution folder?  Those errors come up if you have Pokemon that can't be traded.

**Comment by ttnt5** [comment]
sorry i trade box 9
