### ISSUE TITLE
raid bot restarting error

### ISSUE THREAD

**Issue by ttnt5** [kwsch/SysBot.NET#40]
i run raid bot
and all participants have joined but not start
it start 3minutes over and run
and Restarting the game
![캡처](https://user-images.githubusercontent.com/61551694/75608979-f9cd2c00-5b47-11ea-9766-6288972dc83f.PNG)
i wait one minute but nothing happened

**Comment by hp3721** [comment]
Please read the wiki. Currently the raid bot is a work in progress and isn't fully complete.

**Comment by architdate** [comment]
What exactly happens on the switch before the game is restarted? (At what stage is it stuck?)

**Comment by kwsch** [comment]
ldn-mitm is currently a requirement

**Comment by ttnt5** [comment]
> What exactly happens on the switch before the game is restarted? (At what stage is it stuck?)

first error
all participants have joined but not started
3minutes over and start
second error
restarting the game and not enter the y command
i wait 2minutes but still not working

**Comment by architdate** [comment]
> > What exactly happens on the switch before the game is restarted? (At what stage is it stuck?)
> 
> first error
> all participants have joined but not started
> 3minutes over and start
> second error
> restarting the game and not enter the y command
> i wait 2minutes but still not working

Okay, then it's working as expected!
It isn't pressing Y for you because you do not have ldn_mitm as @kwsch specified
