### ISSUE TITLE
Bot won´t connect to Twitch after compiling new Version

### ISSUE THREAD

**Issue by Shinyhunter2109** [kwsch/SysBot.NET#43]
Hey i noticed that my Twitchbot won´t connect to my twitch after i compiled the latest Changes . Discord works fine only on  twitch it´s not appearing in Chat.

**Comment by kwsch** [comment]
Use a commit from >17h ago until the new features are thoroughly tested https://github.com/kwsch/SysBot.NET/commit/ed6ea1f32009fb506b745069359121ba68675cf0

**Comment by kwsch** [comment]
Ensure your settings are filled out; a couple of days ago the config file was reworked and will be default values if you update from old versions.

**Comment by Shinyhunter2109** [comment]
Okay i will do thanks for your time and help :)
