### ISSUE TITLE
Issue with building project

### ISSUE THREAD

**Issue by GyroFalc** [kwsch/SysBot.NET#6]
I've tried to (re)build the project multiple times using Visual Studio 2019, but keep encountering errors. 

Steps taken trying to resolve the issue:
- Installed .NET Framework 4.7 Developer Pack
- Installed [z3win_AnyCPU](https://www.nuget.org/packages/z3win_AnyCPU/4.5.0.5) using NuGet Package Manager
- Uninstalled [z3win_AnyCPU](https://www.nuget.org/packages/z3win_AnyCPU/4.5.0.5), replaced with [z3x86_win](https://www.nuget.org/packages/z3x86win/4.5.0.1)
- Uninstalled [z3x86_win](https://www.nuget.org/packages/z3x86win/4.5.0.1), replaced with [z3x64_win](https://www.nuget.org/packages/z3x64win/4.5.0.1)

Errors given back:

|Description | Project | File | Line |
| --- | --- | --- | --- | 
|'Model' does not contain a definition for 'Consts' and no accessible extension method 'Consts' accepting a first argument of type 'Model' could be found (are you missing a using directive or an assembly reference?) | SysBot.Pokemon (netstandard2.0) | SysBot.NET-master\SysBot.Pokemon\Util\Z3Search.cs | 53 |

All others are metadata files not being present like SysBot.Pokemon.dll.
I assume this is because of SysBot.Pokemon not building successfully

**Comment by Bappsack** [comment]
select the x64 build option.

**Comment by GyroFalc** [comment]
Thanks, that did fix the issue.
