### ISSUE TITLE
HUB Suggestion!!!

### ISSUE THREAD

**Issue by edwarbad23** [kwsch/SysBot.NET#68]
I posted this on Discord Server but said me to post here, I have a suggestion, it's possible to add to the HUB menu the amount the time to bot wait while the system it's connecting to internet (ex. to connect on the Y-comm, the time to wait when you enter to the raid and the time to wait when you host the raid)? It's would for the slow switch internet connection!

In the afternoon, my internet caused slowly internet connection, so the bot and the game were desinchronized in pressing buttons or hosting the raid without code or always change pokemon, so I think if the bot have these settings in the HUB menu It would be more easily for the switch with the slowly internet connection!!

I add pictures to see what I mean!!

![IMG_20200524_214238](https://user-images.githubusercontent.com/21049981/82837062-aab83e00-9e8d-11ea-9faa-4c93baaa4218.jpg)
![IMG_20200524_214316](https://user-images.githubusercontent.com/21049981/82837063-abe96b00-9e8d-11ea-82fb-4a2c0f9623eb.jpg)
ugge
![IMG_20200524_214340](https://user-images.githubusercontent.com/21049981/82837068-ad1a9800-9e8d-11ea-8d14-126fb2d07fde.jpg)

**Comment by Lusamine** [comment]
Added two settings in https://github.com/kwsch/SysBot.NET/commit/3456c3a63086b86d176d459d53b554e711e5c44b under ``FeatureToggle > ExtraTimeReconnectYComm`` and ``Raid > ExtraTimeOpenRaid``. This also helps users with faster internet since they aren't forced to wait a longer time than necessary.
