### ISSUE TITLE
You forgot 1 suggestion

### ISSUE THREAD

**Issue by edwarbad23** [kwsch/SysBot.NET#69]
Hi, it's me again, thnx you very much to add the settings to the hub, but you forgot 1 suggestion and it's when you enter to the raid (after you connected in the y-comm), you have to wait a certain time until you put the code (press +), well in slow switch connection, you have to wait more time than the normal / faster switch connection, so If you can add 1 more setting tho the HUB I really appreciate it.

P.D1: Fortunately, I still had slow internet, and I tested with the new sysbot, and works but not in the part that I mention you
P.D2: If you check my previous issue, it's the second photo!!

Thnx!!!

**Comment by Lusamine** [comment]
Your internet must be really slow!  I added this in https://github.com/kwsch/SysBot.NET/commit/86b9b00e4c8496bfedfee140f3af26768825c54a.
