### ISSUE TITLE
Illegal Ball Combo Upon Injection

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/SysBot.NET#7]
Using the trade command with the following showdown text:
```
Rowlet (M) @ Master Ball
Ability: Overgrow
Level: 5
Shiny: Yes
EVs: 236 Atk / 36 SpD / 180 Spe
Jolly Nature
- Swords Dance
- Brave Bird
- Leaf Blade
- Sucker Punch
```
Results in an untradeable Pokemon. AutoLegalityMod puts Rowlett in a Friend Ball because it's green, which Rowlett can never be caught in.

Would it be possible to include a toggle for the "Pokeball based on color" functionality? Or an override to designate which ball you'd like a Pokemon in? Pehaps --Pokeball ? Or something like that?
Thank you.

**Comment by kwsch** [comment]
Has already been fixed in base PKHeX commits; I can add a couple settings to toggle ALM stuff when starting.

**Comment by greenDarkness** [comment]
Apologies, should have check there first. ALM toggles would be great though. Thanks so much!
