### ISSUE TITLE
RaidBot: Crashes when closing the game

### ISSUE THREAD

**Issue by kaelitokael** [kwsch/SysBot.NET#70]
Hi,

My switch/atmosphere crashes when the bot closes the game after running multiple raids (around 25-34 runs). I've looked through the closed issues, and the troubleshooting as well. I'm using sysbot-base version 1.3 and ldn_mitm 1.3.4, and a stable network connection. These are my Homebrew apps: Checkpoint, FTPD, JKSV, ldn_mitm, nxdumptool, Lockpick.

The screen shows error 2168-0002 (0x4a8), program 4200000000000010.

Please let me know if it's already reported, or you have any idea how to fix this. I might have missed it out.

Thanks!

**Comment by Lusamine** [comment]
Ensure that you are using the "fix memory leak" branch of ldm_mitm here: https://github.com/spacemeowx2/ldn_mitm/tree/fix-memoryleak

This is also pinned in our sysbot-bugs channel.  The public release is known to cause crashes even without SysBot: https://github.com/spacemeowx2/ldn_mitm/issues/43

**Comment by kaelitokael** [comment]
It worked! Thank you @Lusamine !!!
