### ISSUE TITLE
RaidBot: Full Party not starting

### ISSUE THREAD

**Issue by kaelitokael** [kwsch/SysBot.NET#71]
Hi,

The raidbot is not starting even if the party is full, tho it works sometimes. I've checked the value of BitConverter.ToUInt32(data, 0) in GetRaidPartyIsFullAsync, but its giving the same value everytime.

Thanks!

**Comment by Lusamine** [comment]
I'm not able to replicate this.  The most common reason for offsets not to work is hosting hacked raids or using any additional methods to sideload hacked raid rewards.  If you're not doing either of these, I would suggest joining the Discord server with full details of what you're doing to cause this to happen.

**Comment by kaelitokael** [comment]
Hi @Lusamine ,

I think I found the cause. It happens when the console is docked. Is it recommended to undock the switch when using the bot?

Thanks!

**Comment by Lusamine** [comment]
There are other problems that happen when docking, but I've never heard of this happening due to it.  Usually it's a controller issue that happens.

**Comment by kaelitokael** [comment]
I'll talk to you in discord then :) Thank you!
