### ISSUE TITLE
Twitch integration stops working with invalid nickname request

### ISSUE THREAD

**Issue by BobandyLive** [kwsch/SysBot.NET#72]
I stumbled upon an issue that's been causing major issues with my SysBot on Twitch over the last couple days. If a user requests a Pokemon without a nickname but puts the name of the pokemon in parenthesis, the bot will stop processing commands on Twitch. It will still keep going through random distributions and work on Discord, but it completely breaks the Twitch commands when it happens.

For example, if you go into your Twitch chat and do the following request it will trigger the issue:
$trade (Pikachu)

As a temporary solution I've added the following moderation filter on my Twitch account which blocks people from making these types of requests:
"$trade (*"

I've instructed my users not to do this obviously, but if someone wants to be malicious and continue to break the bots on Twitch that can be a major headache.

**Comment by Lusamine** [comment]
Just wondering, do you have brute force on?  This is not recommended because it is CPU intensive and can tie up the bot trying to process something that won't work at all.

**Comment by BobandyLive** [comment]
I do and I thought perhaps that was causing the issue so I tried disabling it and it was still happening even with brute force turned off.

**Comment by architdate** [comment]
I recommend you always turn off bruteforce, but ill fix this issue internally too
