### ISSUE TITLE
exception for ditto to get correct nature (and not get minted)

### ISSUE THREAD

**Issue by matxx** [kwsch/SysBot.NET#73]
Hi,

I've used the twitch stream [OaksLab](https://www.twitch.tv/oakslab) to get a ditto of an Adamant one. But, it was not of the correct nature, the ditto had another nature and an adamant mint want used to change the apparent nature.

The problem is : I want to use the nature of ditto to pass it down when breeding and it is not possible.

Would be great if ditto had the exact nature we asked.

**Comment by Lusamine** [comment]
SysBot leverages AutoLegality Mod to generate its Pokemon. Ditto in Gen8 are generated from raids, which follow xoroshiro: https://github.com/Admiral-Fish/RNGWriteups/blob/master/Gen%208/Raid%20Generation.md

That means it's not simple to create a fully legal Pokémon matching all your desired traits. ALM is intended for competitive Pokémon, so minting and Hyper Training are acceptable if it's not easy to find a legal encounter.

I believe that OaksLab discloses that they do not generate perfect breeding Ditto. It's possible to ignore xoroshiro for perfect stats and less legal, but that's up to the bot owner, not us.
