### ISSUE TITLE
Sys-Bot keeps crashing

### ISSUE THREAD

**Issue by unkillablesnow** [kwsch/SysBot.NET#74]
hey there, pretty new to all this but i watched some tutorials of how to get Sys-bot into discord to use to trade pokemon to my switch without having to mod my console, unfortunately Sys-bot will crash as soon as i hit start and leaves me waiting in the queue for my shiny pokemon.
have i set something up wrong or what im so very confused as i did just like i saw but mine wont work

**Comment by Lusamine** [comment]
[Read the wiki](https://github.com/kwsch/SysBot.NET/wiki).  YOU CANNOT RUN SYSBOT IF YOUR SWITCH IS NOT HACKED.  Of course it will crash because it cannot connect to an unhacked console.

You do not need a hacked console to use someone else's SysBot.

**Comment by unkillablesnow** [comment]
ok well every tutorial on youtube ive watched was literally talking about how to use sys-bot through you're own discord without a modded switch! literrally watched 20 different youtubers who do not have modded consoles use there own discord with a sys-bot and trade shiny pokemon to themself, they even say they dont have CFW, i followed there videos to the T and so far had my sys-bot connect once for 15 minutes before my wifi cut and the bot crashed again, if you're saying i HAVE to have CFW then why didn't anyone ive seen?

**Comment by Lusamine** [comment]
Please read the instructions before opening issues.
You are trying to HOST a sysbot which requires CFW.
Using someone else's sysbot does not require CFW, nor does it require you to use anything on our repo.
