### ISSUE TITLE
Accidental Moronic Code Added

### ISSUE THREAD

**Issue by somerandominternetuser** [kwsch/SysBot.NET#75]
https://github.com/kwsch/SysBot.NET/blob/c8fa4c82eaade2d91074442fe76313485a1c8caa/SysBot.Pokemon.WinForms/Main.cs#L134

Looks like some moron must have accidentally left this code here. I can't imagine anyone would intentionally be so immature, so I assume it's an accident and needs to be removed.

A programmer with half a brain would have simply updated the README file to include a notice about DLC support being actively worked on, rather than breaking existing functionality - which is why I can't imagine this was intentional. Why would someone with less than half a brain be allowed to work on the project?

**Comment by sora10pls** [comment]
Why would someone with less than half a brain not be able to take a joke?

**Comment by Lusamine** [comment]
Seems to be working fine for me.

**Comment by architdate** [comment]
Yeah, I agree with OP, what an absolute moron who committed that. Can't imagine anyone who would be that immature. They really shouldn't allow such brainlets to commit to these repos. Thank you somerandominternetuser for your amazing insight on the matter!

**Comment by Rino6357** [comment]
Sysbot still works for me tho, dlc support and everything ;)
