### ISSUE TITLE
Event Pokemon not trading 

### ISSUE THREAD

**Issue by gaymerstevie** [kwsch/SysBot.NET#76]
When using the bot for link trades by injecting legal pk8 files it still is not allowing event Pokemon to be found via the sysbot. When they are put into the distribute folder when you go to run the bot it’s says nothing to be checked. is there any way this will be updated to allow event Pokémon in cherish ball to be traded?

**Comment by Lusamine** [comment]
Event Pokemon can be traded.  What files are you trying to trade?

**Comment by gaymerstevie** [comment]
When trading via the distribute so injecting Pokemon into your game and trading them I am having problems with any cherish ball Pokemon so eg. Pikahats eclipse solgalo
 any in cherish ball will not trade and will always come up with this

**Comment by gaymerstevie** [comment]
![image](https://user-images.githubusercontent.com/67427749/85744436-cf0d7180-b6fc-11ea-8a94-d0728834ea94.jpg)

**Comment by Lusamine** [comment]
Do you have distribution turned on?

**Comment by gaymerstevie** [comment]
And these are legal Pokemon I have gotten through the events

**Comment by gaymerstevie** [comment]
What do you mean have it on as other Pokemon trade

**Comment by gaymerstevie** [comment]
![image](https://user-images.githubusercontent.com/67427749/85744870-227fbf80-b6fd-11ea-86a7-5f6c1595ad02.jpg)

**Comment by gaymerstevie** [comment]
These are the settings I use

**Comment by Lusamine** [comment]
Can't replicate this as my bot is giving away stuff fine, even with event Pokemon.  Join the Discord and see if someone can figure out what you're doing wrong.

**Comment by gaymerstevie** [comment]
where is the discord

**Comment by Lusamine** [comment]
https://github.com/kwsch/SysBot.NET Linked on the front page :P
