### ISSUE TITLE
Randomly changing box

### ISSUE THREAD

**Issue by SystemAnonymous** [kwsch/SysBot.NET#78]
Hey guys, thank you for the great work with SysBot. 

I am having a constant issue and can not seem to fix it. So whilst being a Link-Trade bot. It works for a couple hours, then randomly it changes to a different box and starts trading the pokemon from that box. 

I never experienced this issue before the DLC update. And I've looked through the logs and can not even seem to find the error anywhere. Other than

"Entering trade code : 0000 0000
Waiting for trainer....
Resetting bot position"

I've looked around and cant find a fix for this either.

Sorry if a dumb question.

Please can you help me?
Kind Regards.

**Comment by Lusamine** [comment]
Generally a sys-botbase issue.  See the wiki: https://github.com/kwsch/SysBot.NET/wiki/Troubleshooting

**Comment by SystemAnonymous** [comment]
Sorry but. There is nothing on the wiki about this issue. I'm on 1.3 as recommended.
And never had any issues at all until the DLC drop. 

So I have no idea how to fix this.

**Comment by Lusamine** [comment]
Join the Discord server as the wiki recommends and see if someone can figure out your issue.
