### ISSUE TITLE
Stop Conditions for Sysbot Settings set with 31/31/31/31/31/31 IVs but EggFetch Stopped at Incorrect Target

### ISSUE THREAD

**Issue by bell4631** [kwsch/SysBot.NET#95]
## Description

Using the EggFetch functionality of Sysbot, the user configured the Sysbot settings so that the bot would stop with the target IVs. After depositing the two Pokemon in the daycare center on Route 5, the bot was turned on and left alone and stop when its search was completed. The bot unexpectedly stopped just after one fetch, with IVs that did not match the target set in the stop conditions.

## Expected Behavior

When a user sets the stop conditions under Sysbot settings, the EggFetch Bot shall stop as soon as it matches the IVs set by the user.

## Actual Behavior

Eggfetch bot stopped when it found an egg that did not match the IVs set by the user

## Steps to Reproduce

1. Under stop conditions for sysbot settings, set the target IVs in the configuration "31/31/31/31/31/31"
2. Deposit two Pokemon with High IV scores to use, so the offspring will have 5 max IVs at the least (e.g. "31/x/31/31/31/31)
3. Set up the EggFetch bot as documented before starting
4. Observe the EggFetch stopping as soon as it reaches a target with 5 perfect IVs and not 6 perfect IVs.

## Screenshots

* **Settings of the bot used to find an egg with IVs set to 31 in every stat**

![image](https://user-images.githubusercontent.com/16672751/93091870-4d2a4600-f664-11ea-8cf4-da3344ef0b33.png)

* **Log chat capturing the moment the bot disconnected with incorrect target**

![image](https://user-images.githubusercontent.com/16672751/93092094-9da1a380-f664-11ea-9745-da8d3f302803.png)

## Version

* **Sysbot Version 20200910.1**

**Comment by Lusamine** [comment]
This was fixed recently... are you sure you're on latest commit?

**Comment by bell4631** [comment]
The files that were shown in the Sysbot folder were marked to be modified at around 8:50 PM, dated 9/9/2020. I was sure that I had downloaded the latest version of the bot.

But let me first check to see if either removing/adding the bot again or restarting the program will fix the behavior.

**Comment by Lusamine** [comment]
I am unable to replicate with your steps on latest commit.  Closing this since it's likely settings needed to be updated before the bot was started.

![image](https://user-images.githubusercontent.com/30205550/93095987-6ed9fc00-f669-11ea-89c5-022554a47725.png)
![image](https://user-images.githubusercontent.com/30205550/93096011-76010a00-f669-11ea-8078-324e7d0b528a.png)
