### ISSUE TITLE
When importing Showdown builds the Ultra Shiny Batch Editor commands are ignored.

### ISSUE THREAD

**Issue by Nessus009** [kwsch/SysBot.NET#97]
Hi folks,

First off amazing work! Apologies if this is the incorrect place to post this. I only mean well 😄 

I have noticed that the batch editor commands work great when using Showdown builds for genning on Twitch/Discord etc except one... 

!ShinyXor=0
.PID=$rand
.PID=$shiny

This coding works perfectly fine except when you adjust a Pokémon's IV's below 31 in all stats.

So this guy works perfectly:

.trade Jinn (Gengar-Gmax) (M) @ Life Orb
Ability: Cursed Body  
Shiny: Yes  
Gigantamax: Yes  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature
OT: Nessus
TID: 174663
SID: 2184
OTGender: Male
Ball: Dusk Ball
!ShinyXor=0
.PID=$rand
.PID=$shiny
- Sludge Bomb  
- Shadow Ball  
- Nasty Plot  
- Substitute

But of course would work better with zero attack stat. It makes no difference if I add the zero attack info where Showdown would place it or where PKHeX would place it, still the Pokémon remains star shiny.

Any help would be massively appreciated 😃 

I wasn't sure whether this would be classed as a PKHeX issue or SysBot so I though I'd post here, please don't be mad.

**Comment by Nessus009** [comment]
Apologies but the moves seemed to default to bullet points, sorry!

**Comment by Bappsack** [comment]
Shiny: Square

**Comment by Nessus009** [comment]
> Shiny: Square

HAHA! Look at me making things all difficult! LOL cheers!!
